### ISSUE TITLE
Enum type unknown

### ISSUE THREAD

**Issue by gaetan-hexadog** [wovosoft/laravel-typescript#3]
Hi,

Some of my models have cast attribute to PHP Enum and I get the following error when running the command:

```
Unknown database type enum requested, Doctrine\DBAL\Platforms\MariaDb1027Platform may not support it.
```

regards

**Comment by wovosoft** [comment]
Hi
This feature is not yet available. But it will be available soon.
Thank You

**Comment by rkrater** [comment]
Just installed package(v1.0.7) and got the following
` Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL80Platform may not support it.`

**Comment by wovosoft** [comment]
Thank you,  I will check it
